DELETE  http://localhost:3000/school-admin/school-academic-classes/68373b0cc82f8a6344032868
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzFhZjQxOThlM2Q0M2E4ZDA1ZjJhNCIsImlhdCI6MTc0ODQ0NzkwMywiZXhwIjoxNzQ4NDUxNTAzfQ.ZfnSCvUlC4cIuGKArTm-9DzOxbMwFlbqMY94OsGi2mc