POST http://localhost:3000/school-admin/signin
Content-Type: application/json

// Example of a valid payload for signing in
{
    "username": "9874587895",
    "password": "123456789"
}

# // Invalid payload: Username is missing
# {
#     "password": "123456789"
# }

# // Invalid payload: Password is missing
# {
#     "username": "9874587895"
# }

# // Invalid payload: Username is empty
# {
#     "username": "",
#     "password": "123456789"
# }

# // Invalid payload: Password is empty
# {
#     "username": "9874587895",
#     "password": ""
# }

# // Invalid payload: Username format is invalid
# {
#     "username": "invalid_user",
#     "password": "123456789"
# }

# // Invalid payload: Password is incorrect
# {
#     "username": "9874587895",
#     "password": "wrongpassword"
# }

# // Invalid payload: Contains extra fields not allowed
# {
#     "username": "9874587895",
#     "password": "123456789",
#     "extraField": "notAllowed"
# }