const authResponseMessage = {
  invalidCredentials: "Invalid credentials",
  jwtTokenError: "Not authorize to access this route",
  jwtTokenExpire: "Unauthorized: Access token is expired",
  accountDetailsRequired: "Please provide account details",
  unauthorizedUser: "Unauthorized: Access is denied due to invalid credentials",
  emailOTPInvalid: "Invalid email OTP",
  phoneOTPInvalid: "Invalid phone OTP",
  otpVerificationTimeExpire: "OTP validation time is expired",
  otpSendSuccess: "OTP send successfully on your register email and phone",
  signUpOTPVerificationError: "OTP validation failed please try after sometime",
  signUpOTPVerificationSuccess: `Signup OTP verification process successfully completed`,
  forgottenPasswordFindUserAccountSuccess: "Account details found",
  forgottenPasswordResetPasswordSuccess: "User password reset successfully",
  forgottenPasswordOTPVerificationError: `OTP validation failed please try after sometime`,
  forgottenPasswordFindUserAccountError: `This account details are not present in over database`,
  forgottenPasswordOTPVerificationSuccess: `Forgotten password OTP verification process successfully completed`,
  forgottenPasswordResetPasswordError: `User password is not reset right now, Please after sometime`,
  superAdminSignUpError: "Super admin already exist in our database",
  superAdminSignUpSuccess: "Super admin signup process successfully completed",
  superAdminSignUpDBError: `Super admin signup process failed, Please try after sometime`,
  superAdminSignUpActivationError: `Super admin account activation failed, Please try after sometime`,
  superAdminSignInSuccess: "Super admin signin process successfully completed",
  superAdminPasswordChangedSuccess: "Super admin password changed successfully",
  superAdminPasswordChangedError: `Super admin password changed failed, Please try after sometime`,
  schoolAdminDetailsRequired: "School admin details are required",
  schoolAdminProfilePutSuccess: `School admin profile updated successfully`,
  schoolAdminProfilePutError: `Facing issue while updating school admin profile details`,
  schoolAdminChangePasswordSuccess: `School admin password updated successfully`,
  schoolAdminChangePasswordError: `Facing issue while updating school admin password`,
  schoolAdminSignInSuccess: `School admin signin process successfully completed`,
};

module.exports = authResponseMessage;
