const validationConst = {
  usernameMinLength: 5,
  usernameMaxLength: 25,
  passwordMinLength: 5,
  passwordMaxLengthWithoutEncryption: 25,
  passwordMaxLengthWithEncryption: 500,
  firstNameMinLength: 2,
  firstNameMaxLength: 25,
  lastNameMinLength: 2,
  lastNameMaxLength: 25,
  emailMinLength: 5,
  emailMaxLength: 100,
  phoneNumberLength: 10,
  addressMinLength: 10,
  addressMaxLength: 500,
  aadhaarNumberLength: 12,
  organizationNameMinLength: 2,
  organizationNameMaxLength: 100,
  organizationShortNameMinLength: 2,
  organizationShortNameMaxLength: 20,
  governmentRegistrationNumberMaxLength: 20,
  governmentRegistrationNumberMinLength: 2,
  organizationMembersDetailsMinLength: 1,
  organizationMembersDetailsMaxLength: 5,
  organizationMemberPositionMinLength: 2,
  organizationMemberPositionMaxLength: 25,
  schoolNameMinLength: 2,
  schoolNameMaxLength: 200,
  schoolShortNameMinLength: 2,
  schoolShortNameMaxLength: 100,
  schoolEstablishedYearMinNumber: 1700,
  schoolAffiliateNumberMinLength: 2,
  schoolAffiliateNumberMaxLength: 50,
  schoolEducationBoardsMinLength: 1,
  schoolEducationBoardsMaxLength: 5,
};

module.exports = validationConst;
