const validationMessage = {
  firstNameRequired: "First name is required",
  firstNameMaxLength: "First name must be less then 25 characters",
  firstNameMinLength: "First name must be greater then 5 characters",
  lastNameRequired: "Last name is required",
  lastNameMaxLength: "Last name must be less then 25 characters",
  lastNameMinLength: "Last name must be greater then 5 characters",
  emailRequired: "Email is required",
  emailMaxLength: "Email must be less then 100 characters",
  emailMinLength: "Email must be greater then 5 characters",
  emailInvalid: "Invalid email format",
  phoneNumberRequired: "Phone number is required",
  phoneNumberMaxLength: "Phone number must be 10 characters",
  phoneNumberMinLength: "Phone number must be 10 characters",
  phoneNumberInvalid: "Invalid phone number format",
  usernameRequired: "Username is required",
  usernameMaxLength: "Username must be less then 200 characters",
  usernameMinLength: "Username must be greater then 5 characters",
  passwordRequired: "Password is required",
  passwordMaxLength: "Password must be less then 200 characters",
  passwordMinLength: "Password must be greater then 5 characters",
  userIdRequired: "User id is required",
  verificationTokenRequired: "Verification token is required",
  verificationMaxLength: "Verification token must be less then 200 characters",
  verificationMinLength: "Verification token must be greater then 20 characters",
  emailOTPRequired: "Email OTP is required",
  emailOTPMaxLength: "Email OTP must be 6 digit",
  emailOTPMinLength: "Email OTP must be 6 digit",
  phoneOTPRequired: "Phone OTP is required",
  phoneOTPMaxLength: "Phone OTP must be 6 digit",
  phoneOTPMinLength: "Phone OTP must be 6 digit",
  otpExpiryDateTimeRequired: "OTP expiry datetime is required",
  stateNameRequired: "State name is required",
  stateNameMaxLength: "State name must be less then 100 characters",
  stateNameMinLength: "State name must be greater then 2 characters",
  stateNameInvalid: "Invalid state name. No matching state found",
  districtNameRequired: "District name is required",
  districtNameMaxLength: "District name must be less then 100 characters",
  districtNameMinLength: "District name must be greater then 2 characters",
  districtNameInvalid: "Invalid district name. No matching district found",
  cityNameRequired: "City name is required",
  cityNameMaxLength: "City name must be less then 100 characters",
  cityNameMinLength: "City name must be greater then 2 characters",
  cityNameInvalid: "Invalid city. No matching city found",
  areaNameRequired: "Area name is required",
  areaNameMaxLength: "Area name must be less then 100 characters",
  areaNameMinLength: "Area name must be greater then 2 characters",
  areaNameInvalid: "Invalid area name. No matching area name found",
  zipcodeRequired: "Zipcode is required",
  invalidZipcode: "Invalid zipcode",
};

module.exports = validationMessage;
