const responseMessage = {
  resourceNotFound: "Resource not found with id of",
  resourceNotFoundMessage: "Resource not found",
  invalidCredentials: "Invalid credentials",
  unauthorizedUser: "Unauthorized: Access is denied due to invalid credentials",
  jwtTokenExpire: "Unauthorized: Access token is expired",
  jwtTokenError: "Not authorize to access this route",
  duplicateField: "Duplicate field value entered",
  invalidFormat: "Invalid format",
  serverError: "Something went wrong please try again",
  studentSignUpSuccess: "Student Signup process successfully completed",
  studentSignInSuccess: "Students signin process successfully completed",
  otpSendSuccess: "OTP send successfully on your register email and phone",
  emailOTPInvalid: "Invalid email OTP",
  phoneOTPInvalid: "Invalid phone OTP",
  otpVerificationTimeExpire: "OTP validation time is expired",
  signUpOTPVerificationError: "OTP validation failed please try after sometime",
  signUpOTPVerificationSuccess: "Signup OTP verification process successfully completed",
  forgottenPasswordOTPVerificationError: "OTP validation failed please try after sometime",
  forgottenPasswordOTPVerificationSuccess: "Forgotten password OTP verification process successfully completed",
  accountDetailsRequired: "Please provide account details",
  forgottenPasswordFindUserAccountError: "This account details are not present in over database",
  forgottenPasswordFindUserAccountSuccess: "Account details found",
  forgottenPasswordResetPasswordSuccess: "User password reset successfully",
  forgottenPasswordResetPasswordError: "User password is not reset right now, Please after sometime",
};

module.exports = responseMessage;
