const responseMessage = {
  resourceNotFound: "Resource not found with id of",
  resourceNotFoundMessage: "Resource not found",
  invalidCredentials: "Invalid credentials",
  unauthorizedUser: "Unauthorized: Access is denied due to invalid credentials",
  jwtTokenExpire: "Unauthorized: Access token is expired",
  jwtTokenError: "Not authorize to access this route",
  duplicateField: "Duplicate field value entered",
  invalidFormat: "Invalid format",
  serverError: "Something went wrong please try again",
  studentSignUpSuccess: "Student Signup process successfully completed",
  studentSignInSuccess: "Students signin process successfully completed",
  otpSendSuccess: "OTP send successfully on your register email and phone",
  emailOTPInvalid: "Invalid email OTP",
  phoneOTPInvalid: "Invalid phone OTP",
  otpVerificationTimeExpire: "OTP validation time is expired",
  signUpOTPVerificationError: "OTP validation failed please try after sometime",
  signUpOTPVerificationSuccess: "Signup OTP verification process successfully completed",
  forgottenPasswordOTPVerificationError: "OTP validation failed please try after sometime",
  forgottenPasswordOTPVerificationSuccess: "Forgotten password OTP verification process successfully completed",
  accountDetailsRequired: "Please provide account details",
  forgottenPasswordFindUserAccountError: "This account details are not present in over database",
  forgottenPasswordFindUserAccountSuccess: "Account details found",
  forgottenPasswordResetPasswordSuccess: "User password reset successfully",
  forgottenPasswordResetPasswordError: "User password is not reset right now, Please after sometime",
  superAdminSignUpError: "Super admin already exist in our database",
  superAdminSignUpSuccess: "Super admin signup process successfully completed",
  superAdminSignUpDBError: "Super admin signup process failed, Please try after sometime",
  superAdminSignUpActivationError: "Super admin account activation failed, Please try after sometime",
  superAdminSignInSuccess: "Super admin signin process successfully completed",
  superAdminPasswordChangedSuccess: "Super admin password changed successfully",
  superAdminPasswordChangedError: "Super admin password changed failed, Please try after sometime",
  statesGetRequestSuccess: "States details found successfully",
  statePostRequestSuccess: "New state added successfully",
  statePostRequestFail: "Facing issue while adding new state details",
  statePutRequestSuccess: "State details updated successfully",
  statePutRequestFail: "Facing issue while updating state details",
  stateDeleteRequestSuccess: "State details deleted successfully",
  stateDeleteRequestFail: "Facing issue while deleting state details",
  districtsGetRequestSuccess: "Districts details found successfully",
  districtPostRequestSuccess: "New district added successfully",
  districtPostRequestFail: "Facing issue while adding new district details",
  districtPutRequestSuccess: "District details updated successfully",
  districtPutRequestFail: "Facing issue while updating district details",
  districtDeleteRequestSuccess: "District details deleted successfully",
  districtDeleteRequestFail: "Facing issue while deleting district details",
  citiesGetRequestSuccess: "Cities details found successfully",
  cityPostRequestSuccess: "New city added successfully",
  cityPostRequestFail: "Facing issue while adding new city details",
  cityPutRequestSuccess: "City details updated successfully",
  cityPutRequestFail: "Facing issue while updating city details",
  cityDeleteRequestSuccess: "City details deleted successfully",
  cityDeleteRequestFail: "Facing issue while deleting city details",
  areaNamesGetRequestSuccess: "Area names details found successfully",
  areaNamePostRequestSuccess: "New area name added successfully",
  areaNamePostRequestFail: "Facing issue while adding new area name details",
  areaNamePutRequestSuccess: "Area name details updated successfully",
  areaNamePutRequestFail: "Facing issue while updating area name details",
  areaNameDeleteRequestSuccess: "Area name details deleted successfully",
  areaNameDeleteRequestFail: "Facing issue while deleting area name details",
  zipcodesGetRequestSuccess: "Zipcodes details found successfully",
  zipcodePostRequestSuccess: "New zipcode added successfully",
  zipcodePostRequestFail: "Facing issue while adding new zipcode details",
  zipcodePutRequestSuccess: "Zipcode details updated successfully",
  zipcodePutRequestFail: "Facing issue while updating zipcode details",
  zipcodeDeleteRequestSuccess: "Zipcode details deleted successfully",
  zipcodeDeleteRequestFail: "Facing issue while deleting zipcode details",
  schoolTypeGetRequestSuccess: "School type details found successfully",
  schoolTypePostRequestSuccess: "New school type added successfully",
  schoolTypePostRequestFail: "Facing issue while adding new school type details",
  schoolTypePutRequestSuccess: "School type details updated successfully",
  schoolTypePutRequestFail: "Facing issue while updating school type details",
  schoolTypeDeleteRequestSuccess: "School type details deleted successfully",
  schoolTypeDeleteRequestFail: "Facing issue while deleting school type details",
  eductionBoardGetRequestSuccess: "Eduction board details found successfully",
  eductionBoardPostRequestSuccess: "New eduction board added successfully",
  eductionBoardPostRequestFail: "Facing issue while adding new eduction board details",
  eductionBoardPutRequestSuccess: "Eduction board details updated successfully",
  eductionBoardPutRequestFail: "Facing issue while updating eduction board details",
  eductionBoardDeleteRequestSuccess: "Eduction board details deleted successfully",
  eductionBoardDeleteRequestFail: "Facing issue while deleting eduction board details",
};

module.exports = responseMessage;
