DELETE http://localhost:3000/super-admin/academic-classes/6835c87aac967abcb357e4d1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGJkOTE5MGNkYzJmOTFjOWI0MmIwZSIsImlhdCI6MTc0ODM1NDgwMSwiZXhwIjoxNzQ4Mzk4MDAxfQ.xhVh1QNA2F_lT6AybcJqN6UT7Nqyfi-AmM0uclwF2dc

