POST http://localhost:3000/super-admin/states
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjM1MWMyYzRjMzZkN2MxNWI1ZjBiNSIsImlhdCI6MTc0NzE1MjkyMSwiZXhwIjoxNzQ3MTk2MTIxfQ.MdM8dzKlDwcwD4cz7s9N9MaGY_KjEyKH4KM1impL_4Y