const admissionApplicationValidationMessage = {
  admissionApplicationReqBodyRequired: "Request body is required",
  admissionApplicationReqBodyEmpty: "Request body cannot be empty",
  admissionApplicationReqBodyBase: "Request body must be an object",
  admissionApplicationReqBodyUnknown: "Request body contains unknown fields",
  admissionApplicationStatusRequired: `Admission application status is required`,
  admissionApplicationStatusInvalid: `Admission application status must be one of the following values: draft, submitted`,
  admissionApplicationStatusEmpty: `Admission application status cannot be empty`,
  admissionApplicationStatusBase: `Admission application status must be a string`,
  admissionApplicationSchoolAcademicClassBase: `School academic class must be a string`,
  admissionApplicationSchoolAcademicClassEmpty: `School academic class cannot be empty`,
  admissionApplicationSchoolAcademicClassRequired: `School academic class is required`,
  admissionApplicationSchoolAcademicClassInvalid: `School academic class must be a valid ObjectId`,
  admissionApplicationSchoolAcademicClassNotFound: `School academic class not found`,
  admissionApplicationDuplicateExists: `An admission application for this student, academic class and academic session already exists`,
  admissionApplicationValidationError: `Facing issues while validating admission application data please try again later`,
  admissionApplicationAcademicSessionRequired: "Academic session is required",
  admissionApplicationAcademicSessionInvalid: `Academic session must be in the format "YYYY-YYYY" with consecutive years (e.g., "2025-2026")`,
  admissionApplicationApplicationNumberRequired: `Application number is required`,
  admissionApplicationApplicationNumberEmpty: `Application number cannot be empty`,
  admissionApplicationDocumentVerificationNotesRequired: `Notes are required when a required document is not verified`,
  admissionApplicationDocumentVerificationScheduleDateRequired: `Document verification appointment scheduled date is required`,
  admissionApplicationDocumentVerificationScheduleTimeSlotRequired: `Document verification appointment scheduled time slot is required`,
  admissionApplicationDocumentVerificationScheduleTimeSlotInvalid: `Invalid time slot format. Use 12-hour format 'HH:MM AM/PM - HH:MM AM/PM' (e.g., '10:00 AM - 11:00 AM') with end time after start time`,
  admissionApplicationDocumentVerificationSchedulerRequired: `Document verification appointment booked by user id is required`,
  admissionApplicationFeePaymentDateRequired: `Fee payment appointment scheduled date is required`,
  admissionApplicationFeePaymentTimeSlotRequired: `Fee payment appointment scheduled time slot is required`,
  admissionApplicationFeePaymentTimeSlotInvalid: `Invalid time slot format. Use 12-hour format 'HH:MM AM/PM - HH:MM AM/PM' (e.g., '10:00 AM - 11:00 AM') with end time after start time`,
  admissionApplicationFeePaymentSchedulerRequired: `Fee payment appointment booked by is required`,
};

module.exports = admissionApplicationValidationMessage;
