const {
  emailMaxChar,
  emailMinChar,
  addressMaxChar,
  addressMinChar,
  lastNameMaxChar,
  lastNameMinChar,
  phoneNumberChar,
  firstNameMaxChar,
  firstNameMinChar,
  aadhaarNumberChar,
} = require("@MEHelpers/validationConst");

const commonValidationMessage = {
  firstNameRequired: "First name is required",
  firstNameEmpty: "First name cannot be empty",
  firstNameInvalidFormate: "First name must be string formate",
  firstNameMaxLength: `First name must be less then ${firstNameMaxChar} characters`,
  firstNameMinLength: `First name must be greater then ${firstNameMinChar} characters`,
  lastNameRequired: "Last name is required",
  lastNameEmpty: "Last name cannot be empty",
  lastNameInvalidFormate: "First name must be string formate",
  lastNameMaxLength: `Last name must be less then ${lastNameMaxChar} characters`,
  lastNameMinLength: `Last name must be greater then ${lastNameMinChar} characters`,
  emailRequired: "Email is required",
  emailEmpty: "Email cannot be empty",
  emailInvalid: "Invalid email format",
  emailInvalidFormate: "Email must be string formate",
  emailMaxLength: `Email must be less then ${emailMaxChar} characters`,
  emailMinLength: `Email must be greater then ${emailMinChar} characters`,
  phoneNumberRequired: "Phone number is required",
  phoneNumberEmpty: "Phone number cannot be empty",
  phoneNumberInvalid: "Invalid phone number format",
  phoneNumberInvalidFormate: "Phone number must be string formate",
  phoneNumberMaxLength: `Phone number must be ${phoneNumberChar} characters`,
  phoneNumberMinLength: `Phone number must be ${phoneNumberChar} characters`,
  addressRequired: "Address is required",
  addressEmpty: "Address name cannot be empty",
  addressInvalidFormate: "Address must be string formate",
  addressMaxLength: `Address must be less then ${addressMaxChar} characters`,
  addressMinLength: `Address must be greater then ${addressMinChar} characters`,
  aadhaarNumberRequired: "Aadhaar number is required",
  aadhaarNumberEmpty: "Aadhaar number cannot be empty",
  aadhaarNumberInvalidFormate: "Aadhaar number must be string formate",
  aadhaarNumberMaxLength: `Aadhaar number must be ${aadhaarNumberChar} characters`,
  aadhaarNumberMinLength: `Aadhaar number must be ${aadhaarNumberChar} characters`,
  youtubeURLPattern: "Invalid Facebook URL",
  youtubeURLEmpty: "Youtube URL cannot be empty",
  youtubeURLInvalidFormate: "Youtube URL must be string formate",
  facebookURLPattern: "Invalid Facebook URL",
  facebookURLEmpty: "Facebook URL cannot be empty",
  facebookURLInvalidFormate: "Facebook URL must be string formate",
  instagramURLPattern: "Invalid Instagram URL",
  instagramURLEmpty: "Instagram URL cannot be empty",
  instagramURLInvalidFormate: "Instagram URL must be string formate",
  twitterURLPattern: "Twitter Facebook URL",
  twitterURLEmpty: "Twitter URL cannot be empty",
  twitterURLInvalidFormate: "Twitter URL must be string formate",
};

module.exports = commonValidationMessage;
