const {
  schoolAddressArrayMaxLength,
  latitudeMin,
  latitudeMax,
  longitudeMin,
  longitudeMax,
  campusAreaMin,
  campusAreaMax,
  buildingAreaMin,
  buildingAreaMax,
  outdoorAreaMin,
  outdoorAreaMax,
} = require("@MEHelpers/validationConst");

const schoolAddressValidationMessage = {
  schoolAddressDetailsRequired: `School address details are required`,
  schoolAddressDetailsEmpty: `School address details cannot be empty`,
  schoolAddressDetailsUnknownProperty: `School address details have unknown property`,
  schoolAddressDetailsMustBeObject: `School address details must be an object formate`,
  schoolAddressesDetailsRequired: `School address's details are required`,
  schoolAddressesDetailsEmpty: `School address's details can not be empty`,
  schoolAddressesDetailsMinLength: `Provide at least one school address details`,
  schoolAddressesDetailsMustBeArray: `School address's details must be array formate`,
  schoolAddressesDetailsMaxLength: `Can't add more then ${schoolAddressArrayMaxLength} school address details`,
  latitudeInvalidFormate: `Latitude must be a number`,
  latitudeMinLength: `Latitude must be greater than or equal to ${latitudeMin}`,
  latitudeMaxLength: `Latitude must be less than or equal to ${latitudeMax}`,
  longitudeInvalidFormate: `Longitude must be a number`,
  longitudeMinLength: `Longitude must be greater than or equal to ${longitudeMin}`,
  longitudeMaxLength: `Longitude must be less than or equal to ${longitudeMax}`,
  campusAreaInvalidFormate: `Campus area must be a number`,
  campusAreaMinLength: `Campus area must be greater than or equal to ${campusAreaMin}`,
  campusAreaMaxLength: `Campus area must be less than or equal to ${campusAreaMax}`,
  buildingAreaInvalidFormate: `Building area must be a number`,
  buildingAreaMinLength: `Building area must be greater than or equal to ${buildingAreaMin}`,
  buildingAreaMaxLength: `Building area must be less than or equal to ${buildingAreaMax}`,
  outdoorAreaInvalidFormate: `Outdoor area must be a number`,
  outdoorAreaMinLength: `Outdoor area must be greater than or equal to ${outdoorAreaMin}`,
  outdoorAreaMaxLength: `Outdoor area must be less than or equal to ${outdoorAreaMax}`,
  schoolHoursInvalidFormate: `School hours must be an object`,
  schoolHoursUnknownProperty: `School hours have unknown property`,
  schoolHoursDayInvalidFormate: `School hours day must be an object`,
  schoolHoursDayUnknownProperty: `School hours day have unknown property`,
  schoolHoursOpenTimeInvalidFormate: `School hours open time must be in HH:mm format`,
  schoolHoursOpenTimeEmpty: `School hours open time cannot be empty`,
  schoolHoursOpenTimeInvalid: `School hours open time must be in HH:mm format`,
  schoolHoursCloseTimeInvalidFormate: `School hours close time must be in HH:mm format`,
  schoolHoursCloseTimeEmpty: `School hours close time cannot be empty`,
  schoolHoursCloseTimeInvalid: `School hours close time must be in HH:mm format`,
  administrativeHoursInvalidFormate: `Administrative hours must be an object`,
  administrativeHoursUnknownProperty: `Administrative hours have unknown property`,
  administrativeHoursDayInvalidFormate: `Administrative hours day must be an object`,
  administrativeHoursDayUnknownProperty: `Administrative hours day have unknown property`,
  administrativeHoursOpenTimeInvalidFormate: `Administrative hours open time must be in HH:mm format`,
  administrativeHoursOpenTimeEmpty: `Administrative hours open time cannot be empty`,
  administrativeHoursOpenTimeInvalid: `Administrative hours open time must be in HH:mm format`,
  administrativeHoursCloseTimeInvalidFormate: `Administrative hours close time must be in HH:mm format`,
  administrativeHoursCloseTimeEmpty: `Administrative hours close time cannot be empty`,
  administrativeHoursCloseTimeInvalid: `Administrative hours close time must be in HH:mm format`,
};

module.exports = schoolAddressValidationMessage;
