const { maxFeeAmount, minFeeAmount } = require("@MEHelpers/validationConst");

const schoolFeeValidationMessage = {
  schoolFeeNotFound: `School fee not found in database`,
  schoolFeeIdRequired: `School fee id is required`,
  schoolFeeIdEmpty: `School fee id can't be empty`,
  schoolFeeIdBase: `School fee id must be string formate`,
  schoolFeeIdNotFound: `School fee id not found in database`,
  schoolFeeIdInvalid: `Invalid school fee id. No matching school fee id`,
  schoolFeeReqBodyRequired: "School fee request body is required",
  schoolFeeReqBodyEmpty: "School fee request body can't be  empty",
  schoolFeeReqBodyBase: "School fee request body has invalid formate",
  schoolFeeReqBodyUnknown: "School fee request body has unknown parameters",
  monthlyFeeRequired: "Monthly fee is required.",
  monthlyFeeInvalidFormate: `Monthly fee must be number formate`,
  monthlyFeePositiveNumber: `Monthly fee must be a positive number`,
  monthlyFeeMinAmount: `Monthly fee must be at greater than ${minFeeAmount} rupees.`,
  monthlyFeeMaxAmount: `Monthly fee must be at most ${maxFeeAmount} rupees.`,
  quarterlyFeeRequired: "Quarterly fee is required.",
  quarterlyFeeInvalidFormate: `Quarterly fee must be number formate`,
  quarterlyFeePositiveNumber: `Quarterly fee must be a positive number`,
  quarterlyFeeMinAmount: `Quarterly fee must be at greater than ${minFeeAmount} rupees.`,
  quarterlyFeeMaxAmount: `Quarterly fee must be at most ${maxFeeAmount} rupees.`,
  halfYearlyFeeRequired: "Half-yearly fee is required.",
  halfYearlyFeeInvalidFormate: `Half-yearly fee must be number formate`,
  halfYearlyFeePositiveNumber: `Half-yearly fee must be a positive number`,
  halfYearlyFeeMinAmount: `Half-yearly fee must be at greater than ${minFeeAmount} rupees.`,
  halfYearlyFeeMaxAmount: `Half-yearly fee must be at most ${maxFeeAmount} rupees.`,
  yearlyFeeRequired: "Yearly fee is required.",
  yearlyFeeInvalidFormate: `Yearly fee must be number formate`,
  yearlyFeePositiveNumber: `Yearly fee must be a positive number`,
  yearlyFeeMinAmount: `Yearly fee must be at greater than ${minFeeAmount} rupees.`,
  yearlyFeeMaxAmount: `Yearly fee must be at most ${maxFeeAmount} rupees.`,
};

module.exports = schoolFeeValidationMessage;
