const {
  schoolNameMaxChar,
  schoolNameMinChar,
  schoolShortNameMaxChar,
  schoolShortNameMinChar,
  schoolAffiliateNumberMaxChar,
  schoolAffiliateNumberMinChar,
  schoolEducationBoardsMaxLimit,
  schoolEstablishedYearMinNumber,
} = require("@MEHelpers/validationConst/validationConst");

const schoolValidationMessage = {
  schoolDetailsEmpty: "School details cannot be empty",
  schoolDetailsRequired: "School details are required",
  schoolDetailsUnknownProperty: "School details have unknown property",
  schoolDetailsMustBeObjectRequired: "School details must be object formate",
  schoolNameRequired: "School name is required",
  schoolNameEmpty: "School name cannot be empty",
  schoolNameInvalidFormate: "School name must be string formate",
  schoolNameInvalid: `Invalid school name. No matching school name found`,
  schoolNameMaxLength: `School name must be less then ${schoolNameMaxChar} characters`,
  schoolNameMinLength: `School name must be greater then ${schoolNameMinChar} characters`,
  schoolShortNameRequired: "School short name is required",
  schoolShortNameEmpty: "School short name cannot be empty",
  schoolShortNameInvalidFormate: "School short name must be string formate",
  schoolShortNameMaxLength: `School short name must be less then ${schoolShortNameMaxChar} characters`,
  schoolShortNameMinLength: `School short name must be greater then ${schoolShortNameMinChar} characters`,
  schoolEstablishedYearMaxYear: `School established year cannot be in the future year`,
  schoolEstablishedYearRequired: `School established year cannot be in the future year`,
  schoolEstablishedYearInvalidFormate: `School established year must be number formate`,
  schoolEstablishedYearPositiveNumber: `School established year must be a positive number`,
  schoolEstablishedYearMinYear: `School established year cannot be earlier than ${schoolEstablishedYearMinNumber}`,
  schoolAffiliateNumberRequired: "Affiliate number is required",
  schoolAffiliateNumberEmpty: "Affiliate number cannot be empty",
  schoolAffiliateNumberInvalidFormate: `Affiliate number must be string formate`,
  schoolAffiliateNumberMaxLength: `Affiliate number must be less then ${schoolAffiliateNumberMaxChar} characters`,
  schoolAffiliateNumberMinLength: `Affiliate number must be greater then ${schoolAffiliateNumberMinChar} characters`,
  schoolWebsiteEmpty: "Website cannot be empty",
  schoolWebsiteInvalidFormate: "Website must be string formate",
  schoolWebsiteURL: "Website must be a valid URL (e.g., https://example.com)",
  schoolEducationBoardsRequired: "School education boards are required",
  schoolEducationBoardsArray: `School education board must have an array values`,
  schoolEducationBoardsMinLength: `At least one school board selection is required`,
  schoolEducationBoardsUnique: `School education board selection have duplicate record.`,
  schoolEducationBoardsMaxLength: `Cannot select more then ${schoolEducationBoardsMaxLimit} school boards`,
};

module.exports = schoolValidationMessage;
