const {
  studentProfileDateOfBirthMaxAge,
  studentProfileDateOfBirthMinAge,
  studentProfileNationalityMinChar,
  studentProfileNationalityMaxChar,
  studentProfileMedicalIssueDetailMinChar,
  studentProfileMedicalIssueDetailMaxChar,
  studentProfileMedicalAllergiesMaxItems,
  aadhaarNumberChar,
} = require("@MEHelpers/validationConst");
const { GENDERS, BLOOD_GROUPS } = require("@ME/helpers/enums/studentEnums");

const studentProfileValidationMessage = {
  studentProfileDateOfBirthRequired: `Student date of birth is required`,
  studentProfileInvalidDateOfBirth: `Date of birth must result in age between ${studentProfileDateOfBirthMinAge} and ${studentProfileDateOfBirthMaxAge} years old`,
  studentProfileGenderRequired: `Gender is required`,
  studentProfileGenderInvalid: `Gender must be one of: ${Object.values(GENDERS).join(", ")}`,
  studentProfileBloodGroupRequired: `Blood group is required`,
  studentProfileBloodGroupInvalid: `Blood group must be one of: ${Object.values(BLOOD_GROUPS).join(", ")}`,
  studentProfileAadhaarNumberRequired: `Aadhaar number is required`,
  studentProfileNationalityRequired: `Nationality is required`,
  studentProfileNationalityBase: `Nationality must be a valid string`,
  studentProfileNationalityEmpty: `Nationality cannot be empty`,
  studentProfileNationalityMaxLength: `Nationality cannot exceed ${studentProfileNationalityMaxChar} characters`,
  studentProfileNationalityMinLength: `Nationality must be at least ${studentProfileNationalityMinChar} characters`,
  hearingIssueDetailsMinLength: `Hearing issue details must be at least ${studentProfileMedicalIssueDetailMinChar} characters`,
  hearingIssueDetailsMaxLength: `Hearing issue details cannot exceed ${studentProfileMedicalIssueDetailMaxChar} characters`,
  hearingIssueDetailsRequired: `hearing_issue_details is required when has_hearing_issue is true`,
  visionIssueDetailsMinLength: `Vision issue details must be at least ${studentProfileMedicalIssueDetailMinChar} characters`,
  visionIssueDetailsMaxLength: `Vision issue details cannot exceed ${studentProfileMedicalIssueDetailMaxChar} characters`,
  visionIssueDetailsRequired: `vision_issue_details is required when has_vision_issue is true`,
  physicalIssueDetailsMinLength: `Physical issue details must be at least ${studentProfileMedicalIssueDetailMinChar} characters`,
  physicalIssueDetailsMaxLength: `Physical issue details cannot exceed ${studentProfileMedicalIssueDetailMaxChar} characters`,
  physicalIssueDetailsRequired: `physical_issue_details is required when has_physical_issue is true`,
  mentalIssueDetailsMinLength: `Mental issue details must be at least ${studentProfileMedicalIssueDetailMinChar} characters`,
  mentalIssueDetailsMaxLength: `Mental issue details cannot exceed ${studentProfileMedicalIssueDetailMaxChar} characters`,
  mentalIssueDetailsRequired: `mental_issue_details is required when has_mental_issue is true`,
  allergiesAtLeastOne: `At least one allergy is required when has_allergies is true`,
  allergiesMinItems: `Must have at least one allergy`,
  allergiesMaxItems: `Cannot add more than ${studentProfileMedicalAllergiesMaxItems} allergies`,
  studentProfileUserBase: `User must be a valid string`,
  studentProfileUserEmpty: `User cannot be empty`,
  studentProfileUserInvalid: `User must be a valid ObjectId`,
  studentProfileUserRequired: `User is required`,
  studentProfileAddressBase: `Address must be a valid string`,
  studentProfileAddressEmpty: `Address cannot be empty`,
  studentProfileAddressInvalid: `Address must be a valid ObjectId`,
  studentProfileAddressRequired: `Address is required`,
  studentProfileFatherBase: `Father must be a valid string`,
  studentProfileFatherEmpty: `Father cannot be empty`,
  studentProfileFatherInvalid: `Father must be a valid ObjectId`,
  studentProfileFatherRequired: `Father is required`,
  studentProfileMotherBase: `Mother must be a valid string`,
  studentProfileMotherEmpty: `Mother cannot be empty`,
  studentProfileMotherInvalid: `Mother must be a valid ObjectId`,
  studentProfileMotherRequired: `Mother is required`,
  studentProfileEmergencyContactsBase: `Emergency contact must be a valid string`,
  studentProfileEmergencyContactsEmpty: `Emergency contact cannot be empty`,
  studentProfileEmergencyContactsInvalid: `Emergency contact must be a valid ObjectId`,
  studentProfileEmergencyContactsRequired: `Emergency contact is required`,
  studentProfileReqBodyBase: `Request body must be an object`,
  studentProfileReqBodyEmpty: `Request body cannot be empty`,
  studentProfileReqBodyUnknown: `Unknown field in request body`,
  studentProfileReqBodyRequired: `Request body is required`,
  studentProfileAadhaarNumberBase: `Aadhaar number must be a valid string`,
  studentProfileAadhaarNumberEmpty: `Aadhaar number cannot be empty`,
  studentProfileAadhaarNumberMinLength: `Aadhaar number must be ${aadhaarNumberChar} characters`,
  studentProfileAadhaarNumberMaxLength: `Aadhaar number must be ${aadhaarNumberChar} characters`,
  studentProfileGenderBase: `Gender must be a valid string`,
  studentProfileGenderEmpty: `Gender cannot be empty`,
  studentProfileBloodGroupBase: `Blood group must be a valid string`,
  studentProfileBloodGroupEmpty: `Blood group cannot be empty`,
  studentProfileDateOfBirthBase: `Date of birth must be a valid date`,
  studentProfileDateOfBirthEmpty: `Date of birth cannot be empty`,
  studentProfilePhotoUrlBase: `Photo URL must be a valid string`,
  studentProfileHasHearingIssueBase: `Has hearing issue must be a boolean`,
  studentProfileHasVisionIssueBase: `Has vision issue must be a boolean`,
  studentProfileHasPhysicalIssueBase: `Has physical issue must be a boolean`,
  studentProfileHasMentalIssueBase: `Has mental issue must be a boolean`,
  studentProfileHasAllergiesBase: `Has allergies must be a boolean`,
  studentProfileAllergiesBase: `Allergies must be an array`,
  studentProfileAllergiesItemBase: `Each allergy must be a valid string`,
};

module.exports = studentProfileValidationMessage;
