### Scenario 001 (Valid payload)
PUT {{schoolAdminLocalhostBaseUrl}}{{schoolAdminUpdateAdmissionApplicationStatusRoute}}
Content-Type: application/json
Authorization: {{schoolAdminAuthToken}}

< ./payload/payload001.json